basePath: /api/v1
host: http://13.214.213.55:1323
info:
  contact:
    email: fgemar72@gmail.com
    name: API Support
    url: https://www.fajargema.com
  description: This is a api for manage finance report.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Finance Report API
  version: "1.0"
paths: {}
swagger: "2.0"
